"""add user settings fields

Revision ID: 12131113135d
Revises: 1406996ff227
Create Date: 2026-05-08 16:47:58.811179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12131113135d'
down_revision = '1406996ff227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # SQLite: ADD COLUMN NOT NULL exige DEFAULT
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=False, server_default='light'))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=False, server_default='pt-br'))
        batch_op.add_column(sa.Column('currency', sa.String(length=5), nullable=False, server_default='BRL'))
        batch_op.add_column(sa.Column('notify_browser', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme', server_default=None)
        batch_op.alter_column('language', server_default=None)
        batch_op.alter_column('currency', server_default=None)
        batch_op.alter_column('notify_browser', server_default=None)
        batch_op.alter_column('notify_email', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_email')
        batch_op.drop_column('notify_browser')
        batch_op.drop_column('currency')
        batch_op.drop_column('language')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
