"""add user admin fields

Revision ID: 1406996ff227
Revises: 
Create Date: 2026-05-08 16:43:41.212508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1406996ff227'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # SQLite não permite ADD COLUMN NOT NULL sem DEFAULT.
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1'))
        )
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0'))
        )
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)

    # Remove defaults (mantém apenas no nível de model)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active', server_default=None)
        batch_op.alter_column('is_admin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
