"""Estrutura inicial completa do banco (baseline unificado)

Revision ID: 2c7da8796725
Revises: 
Create Date: 2026-08-19 11:48:59.063706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7da8796725'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('pagamento_ativo', sa.Boolean(), nullable=False),
    sa.Column('asaas_customer_id', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('notify_browser', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('pct_precificacao_alta', sa.Integer(), nullable=True),
    sa.Column('pct_precificacao_media', sa.Integer(), nullable=True),
    sa.Column('pct_precificacao_baixa', sa.Integer(), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('codigo_verificacao', sa.String(length=6), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('proprietario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proprietario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_papel'), ['papel'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_proprietario_id'), ['proprietario_id'], unique=False)

    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asaas_subscription_id', sa.String(length=60), nullable=True),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('valor_cents', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proximo_vencimento', sa.Date(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assinaturas_asaas_subscription_id'), ['asaas_subscription_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assinaturas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinaturas_user_id'), ['user_id'], unique=False)

    op.create_table('convites_anfitriao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proprietario_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aceito_em', sa.DateTime(), nullable=True),
    sa.Column('anfitriao_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anfitriao_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proprietario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convites_anfitriao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convites_anfitriao_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_convites_anfitriao_proprietario_id'), ['proprietario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convites_anfitriao_token'), ['token'], unique=True)

    op.create_table('financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imovel', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('entrada', sa.Date(), nullable=True),
    sa.Column('saida', sa.Date(), nullable=True),
    sa.Column('bruto', sa.Float(), nullable=True),
    sa.Column('liq_plat', sa.Float(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_user_id'), ['user_id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint'), ['endpoint'], unique=True)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('financeiro_despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financeiro_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['financeiro_id'], ['financeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('ponto_referencia', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('utensilios', sa.Text(), nullable=True),
    sa.Column('regras', sa.Text(), nullable=True),
    sa.Column('foto_principal', sa.String(length=255), nullable=True),
    sa.Column('wifi_rede', sa.String(length=120), nullable=True),
    sa.Column('wifi_senha', sa.String(length=120), nullable=True),
    sa.Column('senha_fechadura', sa.String(length=120), nullable=True),
    sa.Column('ultima_troca_pilha', sa.Date(), nullable=True),
    sa.Column('contato_telefone', sa.String(length=30), nullable=True),
    sa.Column('contato_email', sa.String(length=120), nullable=True),
    sa.Column('email_guia_ativo', sa.Boolean(), nullable=False),
    sa.Column('email_guia_dias_antes', sa.Integer(), nullable=True),
    sa.Column('email_avaliacao_ativo', sa.Boolean(), nullable=False),
    sa.Column('email_avaliacao_dias_depois', sa.Integer(), nullable=True),
    sa.Column('slug_publico', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('checkin_padrao', sa.String(length=5), nullable=True),
    sa.Column('checkout_padrao', sa.String(length=5), nullable=True),
    sa.Column('diaria_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxa_limpeza_padrao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacidade_max', sa.Integer(), nullable=True),
    sa.Column('qtd_quartos', sa.Integer(), nullable=True),
    sa.Column('qtd_banheiros', sa.Integer(), nullable=True),
    sa.Column('qtd_camas', sa.Integer(), nullable=True),
    sa.Column('prazo_cancelamento_gratis', sa.Integer(), nullable=True),
    sa.Column('multa_tipo', sa.String(length=20), nullable=True),
    sa.Column('multa_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('checklist_itens', sa.Text(), nullable=True),
    sa.Column('documentos_ativo', sa.Boolean(), nullable=False),
    sa.Column('documentos_dias_antes', sa.Integer(), nullable=True),
    sa.Column('documentos_campos', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imoveis_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imoveis_slug_publico'), ['slug_publico'], unique=True)
        batch_op.create_index(batch_op.f('ix_imoveis_user_id'), ['user_id'], unique=False)

    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asaas_customer_id', sa.String(length=60), nullable=True),
    sa.Column('asaas_payment_id', sa.String(length=60), nullable=True),
    sa.Column('assinatura_id', sa.Integer(), nullable=True),
    sa.Column('valor_cents', sa.Integer(), nullable=False),
    sa.Column('billing_type', sa.String(length=20), nullable=True),
    sa.Column('invoice_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_asaas_payment_id'), ['asaas_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pagamentos_assinatura_id'), ['assinatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_user_id'), ['user_id'], unique=False)

    op.create_table('despesas_gerais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despesas_gerais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_gerais_imovel_id'), ['imovel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesas_gerais_user_id'), ['user_id'], unique=False)

    op.create_table('estadia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_hospede', sa.String(length=200), nullable=False),
    sa.Column('email_hospede', sa.String(length=120), nullable=True),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('perfil', sa.String(length=30), nullable=False),
    sa.Column('qtd_hospedes', sa.Integer(), nullable=False),
    sa.Column('email_guia_enviado', sa.Boolean(), nullable=False),
    sa.Column('email_avaliacao_enviado', sa.Boolean(), nullable=False),
    sa.Column('token_avaliacao', sa.String(length=64), nullable=True),
    sa.Column('push_checkin_enviado', sa.Boolean(), nullable=False),
    sa.Column('data_checkin', sa.Date(), nullable=False),
    sa.Column('hora_checkin', sa.String(length=5), nullable=False),
    sa.Column('data_checkout', sa.Date(), nullable=False),
    sa.Column('hora_checkout', sa.String(length=5), nullable=False),
    sa.Column('quantidade_dias', sa.Integer(), nullable=False),
    sa.Column('moeda', sa.String(length=5), nullable=False),
    sa.Column('valor_bruto_cents', sa.Integer(), nullable=False),
    sa.Column('valor_liquido_cents', sa.Integer(), nullable=True),
    sa.Column('tem_carro', sa.String(length=3), nullable=False),
    sa.Column('tem_pet', sa.String(length=3), nullable=False),
    sa.Column('detalhe_pet', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('checklist_status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estadia_token_avaliacao'), ['token_avaliacao'], unique=True)

    op.create_table('eventos_precificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('recorrente', sa.Boolean(), nullable=False),
    sa.Column('nivel_impacto', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_precificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_precificacao_imovel_id'), ['imovel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_precificacao_user_id'), ['user_id'], unique=False)

    op.create_table('lembrete_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('intervalo_dias', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_envio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lembrete_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lembrete_configs_imovel_id'), ['imovel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lembrete_configs_user_id'), ['user_id'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estadia_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_hospede', sa.String(length=200), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estadia_id'], ['estadia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_estadia_id'), ['estadia_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_avaliacoes_imovel_id'), ['imovel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_user_id'), ['user_id'], unique=False)

    op.create_table('formularios_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estadia_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tentativas_envio', sa.Integer(), nullable=False),
    sa.Column('data_ultimo_envio', sa.Date(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.Date(), nullable=True),
    sa.Column('respostas_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estadia_id'], ['estadia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formularios_documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formularios_documentos_estadia_id'), ['estadia_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_formularios_documentos_imovel_id'), ['imovel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_documentos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_formularios_documentos_token'), ['token'], unique=True)

    op.create_table('hub_tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=True),
    sa.Column('estadia_id', sa.Integer(), nullable=True),
    sa.Column('lembrete_config_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('email_enviado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estadia_id'], ['estadia.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lembrete_config_id'], ['lembrete_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hub_tarefas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_tarefas_estadia_id'), ['estadia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_tarefas_imovel_id'), ['imovel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_tarefas_lembrete_config_id'), ['lembrete_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_tarefas_user_id'), ['user_id'], unique=False)

    op.create_table('item_estadia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estadia_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estadia_id'], ['estadia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_estadia')
    with op.batch_alter_table('hub_tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_tarefas_user_id'))
        batch_op.drop_index(batch_op.f('ix_hub_tarefas_lembrete_config_id'))
        batch_op.drop_index(batch_op.f('ix_hub_tarefas_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_hub_tarefas_estadia_id'))

    op.drop_table('hub_tarefas')
    with op.batch_alter_table('formularios_documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formularios_documentos_token'))
        batch_op.drop_index(batch_op.f('ix_formularios_documentos_status'))
        batch_op.drop_index(batch_op.f('ix_formularios_documentos_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_formularios_documentos_estadia_id'))

    op.drop_table('formularios_documentos')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_user_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_estadia_id'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('lembrete_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lembrete_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_lembrete_configs_imovel_id'))

    op.drop_table('lembrete_configs')
    with op.batch_alter_table('eventos_precificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_precificacao_user_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_precificacao_imovel_id'))

    op.drop_table('eventos_precificacao')
    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estadia_token_avaliacao'))

    op.drop_table('estadia')
    with op.batch_alter_table('despesas_gerais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_gerais_user_id'))
        batch_op.drop_index(batch_op.f('ix_despesas_gerais_imovel_id'))

    op.drop_table('despesas_gerais')
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_user_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_status'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_assinatura_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_asaas_payment_id'))

    op.drop_table('pagamentos')
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imoveis_user_id'))
        batch_op.drop_index(batch_op.f('ix_imoveis_slug_publico'))
        batch_op.drop_index(batch_op.f('ix_imoveis_grupo_id'))

    op.drop_table('imoveis')
    op.drop_table('financeiro_despesas')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_user_id'))

    op.drop_table('grupos')
    op.drop_table('financeiros')
    with op.batch_alter_table('convites_anfitriao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convites_anfitriao_token'))
        batch_op.drop_index(batch_op.f('ix_convites_anfitriao_proprietario_id'))
        batch_op.drop_index(batch_op.f('ix_convites_anfitriao_email'))

    op.drop_table('convites_anfitriao')
    with op.batch_alter_table('assinaturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assinaturas_user_id'))
        batch_op.drop_index(batch_op.f('ix_assinaturas_status'))
        batch_op.drop_index(batch_op.f('ix_assinaturas_asaas_subscription_id'))

    op.drop_table('assinaturas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_proprietario_id'))
        batch_op.drop_index(batch_op.f('ix_users_papel'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
