"""autoria_em_hub_tarefas

Revision ID: 40be8942cc40
Revises: 2c7da8796725
Create Date: 2026-08-20 17:04:53.241780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40be8942cc40'
down_revision = '2c7da8796725'
branch_labels = None
depends_on = None


def upgrade():
    # Nomes explícitos nas FKs (em vez de deixar o Alembic gerar sem nome):
    # o modo batch do SQLite (usado em dev local) exige constraint nomeada
    # pra conseguir recriar a tabela — sem isso, "flask db upgrade" falha
    # com "Constraint must have a name" em SQLite (funcionaria sem problema
    # no Postgres de produção, mas quebraria pra quem rodar localmente).
    with op.batch_alter_table('hub_tarefas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('concluido_por_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hub_tarefas_concluido_por_id'), ['concluido_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_tarefas_criado_por_id'), ['criado_por_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_hub_tarefas_criado_por_id_users', 'users', ['criado_por_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            'fk_hub_tarefas_concluido_por_id_users', 'users', ['concluido_por_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hub_tarefas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hub_tarefas_criado_por_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_hub_tarefas_concluido_por_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_hub_tarefas_criado_por_id'))
        batch_op.drop_index(batch_op.f('ix_hub_tarefas_concluido_por_id'))
        batch_op.drop_column('concluido_por_id')
        batch_op.drop_column('criado_por_id')

    # ### end Alembic commands ###
