"""adiciona papel ao convite anfitriao (auxiliar)

Revision ID: 843bb7076dfa
Revises: 40be8942cc40
Create Date: 2026-08-27 15:36:10.868908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843bb7076dfa'
down_revision = '40be8942cc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='anfitriao' garante que convites já existentes (linhas
    # antigas, sem essa coluna) sejam preenchidos automaticamente em vez de
    # violar o NOT NULL — todo convite anterior a essa migration era, por
    # definição, um convite de Anfitrião (o tipo Auxiliar não existia ainda).
    with op.batch_alter_table('convites_anfitriao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('papel', sa.String(length=20), nullable=False, server_default='anfitriao'))

    # Remove o server_default depois do backfill: daqui pra frente quem
    # controla o valor padrão é o Python (ConviteAnfitriao.papel default),
    # não o banco — evita os dois ficarem dessincronizados no futuro.
    with op.batch_alter_table('convites_anfitriao', schema=None) as batch_op:
        batch_op.alter_column('papel', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convites_anfitriao', schema=None) as batch_op:
        batch_op.drop_column('papel')

    # ### end Alembic commands ###
