"""add imovel contato fields

Revision ID: a3f9c2e1d8b4
Revises: 12131113135d
Create Date: 2026-07-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f9c2e1d8b4'
down_revision = '12131113135d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato_telefone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('contato_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.drop_column('contato_email')
        batch_op.drop_column('contato_telefone')

    # ### end Alembic commands ###
