"""add despesas_gerais table

Revision ID: b7e4d1f9a2c6
Revises: a3f9c2e1d8b4
Create Date: 2026-07-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e4d1f9a2c6'
down_revision = 'a3f9c2e1d8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'despesas_gerais',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('imovel_id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('categoria', sa.String(length=60), nullable=True),
        sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('observacoes', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('despesas_gerais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_gerais_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesas_gerais_imovel_id'), ['imovel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas_gerais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_gerais_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_despesas_gerais_user_id'))

    op.drop_table('despesas_gerais')

    # ### end Alembic commands ###
